name: "[wardepartmentpapers.org] Hugo Build, Release, Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "preview"
    paths:
      - "**"
      - "!.github/**"

jobs:

  hugo-build-release-deploy:
    uses: chnm/.github/.github/workflows/hugo--build-release-deploy.yml@main
    secrets: inherit
    with:
      runner_labels: '["self-hosted","IncusOS"]'
      hugo-context-root: "."
      hugo-content-path: "/srv"
      hugo-devl-url: "https://pwd.dev.chnm.gmu.edu"
      hugo-prod-url: "https://wardepartmentpapers.org"

      release-tag-name-type: "iso"

      website-devl-fqdn: "pwd.dev.chnm.gmu.edu"
      website-prod-fqdn: "wardepartmentpapers.org"
